# PostgreSQL is the database used.
#

default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  host: localhost
  username: data

development:
  <<: *default
  database: districtatassist_development
  password: Data1$

test:
  <<: *default
  database: districtatassist_test
  password: Data1$

production:
  <<: *default
  database: districtatassist_production
  password: ENV['PRODUCTION_DB_PASSWORD']

